FROM apache/airflow:2.9.3

USER root
RUN apt-get update && apt-get install -y --no-install-recommends git \
 && apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir \
  "sqlalchemy<2.0" \
  "dbt-core==1.10.15" \
  "dbt-postgres==1.9.0"
